/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicBibleRouteImport } from './routes/api/public/bible'
import { Route as ApiPublicFileRouteImport } from './routes/api/public/file'
import { Route as ApiPublicLibraryRouteImport } from './routes/api/public/library'
import { Route as ApiPublicNotificationsRouteImport } from './routes/api/public/notifications'
import { Route as ApiPublicUploadRouteImport } from './routes/api/public/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBibleRoute = ApiPublicBibleRouteImport.update({
  id: '/api/public/bible',
  path: '/api/public/bible',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFileRoute = ApiPublicFileRouteImport.update({
  id: '/api/public/file',
  path: '/api/public/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLibraryRoute = ApiPublicLibraryRouteImport.update({
  id: '/api/public/library',
  path: '/api/public/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotificationsRoute = ApiPublicNotificationsRouteImport.update({
  id: '/api/public/notifications',
  path: '/api/public/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUploadRoute = ApiPublicUploadRouteImport.update({
  id: '/api/public/upload',
  path: '/api/public/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/bible': typeof ApiPublicBibleRoute
  '/api/public/file': typeof ApiPublicFileRoute
  '/api/public/library': typeof ApiPublicLibraryRoute
  '/api/public/notifications': typeof ApiPublicNotificationsRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/bible': typeof ApiPublicBibleRoute
  '/api/public/file': typeof ApiPublicFileRoute
  '/api/public/library': typeof ApiPublicLibraryRoute
  '/api/public/notifications': typeof ApiPublicNotificationsRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/bible': typeof ApiPublicBibleRoute
  '/api/public/file': typeof ApiPublicFileRoute
  '/api/public/library': typeof ApiPublicLibraryRoute
  '/api/public/notifications': typeof ApiPublicNotificationsRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/bible'
    | '/api/public/file'
    | '/api/public/library'
    | '/api/public/notifications'
    | '/api/public/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/bible'
    | '/api/public/file'
    | '/api/public/library'
    | '/api/public/notifications'
    | '/api/public/upload'
  id:
    | '__root__'
    | '/'
    | '/api/public/bible'
    | '/api/public/file'
    | '/api/public/library'
    | '/api/public/notifications'
    | '/api/public/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicBibleRoute: typeof ApiPublicBibleRoute
  ApiPublicFileRoute: typeof ApiPublicFileRoute
  ApiPublicLibraryRoute: typeof ApiPublicLibraryRoute
  ApiPublicNotificationsRoute: typeof ApiPublicNotificationsRoute
  ApiPublicUploadRoute: typeof ApiPublicUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bible': {
      id: '/api/public/bible'
      path: '/api/public/bible'
      fullPath: '/api/public/bible'
      preLoaderRoute: typeof ApiPublicBibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/file': {
      id: '/api/public/file'
      path: '/api/public/file'
      fullPath: '/api/public/file'
      preLoaderRoute: typeof ApiPublicFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/library': {
      id: '/api/public/library'
      path: '/api/public/library'
      fullPath: '/api/public/library'
      preLoaderRoute: typeof ApiPublicLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notifications': {
      id: '/api/public/notifications'
      path: '/api/public/notifications'
      fullPath: '/api/public/notifications'
      preLoaderRoute: typeof ApiPublicNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upload': {
      id: '/api/public/upload'
      path: '/api/public/upload'
      fullPath: '/api/public/upload'
      preLoaderRoute: typeof ApiPublicUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicBibleRoute: ApiPublicBibleRoute,
  ApiPublicFileRoute: ApiPublicFileRoute,
  ApiPublicLibraryRoute: ApiPublicLibraryRoute,
  ApiPublicNotificationsRoute: ApiPublicNotificationsRoute,
  ApiPublicUploadRoute: ApiPublicUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
